# Generated by Django 5.1.15 on 2026-08-21 10:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResultSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(blank=True, max_length=512)),
                ('file_type', models.CharField(max_length=50)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Processing'), ('PROCESSING', 'Processing Document'), ('COMPLETED', 'Analysis Completed'), ('FAILED', 'Processing Failed'), ('EXPIRED', 'Session Expired')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('meta_info', models.JSONField(blank=True, default=dict)),
                ('parsed_dataset', models.JSONField(blank=True, default=dict)),
                ('analytics_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='sessions_ma_created_f67191_idx'), models.Index(fields=['expires_at'], name='sessions_ma_expires_2415ed_idx'), models.Index(fields=['status'], name='sessions_ma_status_692b16_idx')],
            },
        ),
    ]
