# Generated by Django 5.1.15 on 2026-08-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultsession',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Processing'), ('PROCESSING', 'Processing Document'), ('PENDING_VERIFICATION', 'Pending Human Verification'), ('VERIFIED', 'Verified by User'), ('COMPLETED', 'Analysis Completed'), ('FAILED', 'Processing Failed'), ('EXPIRED', 'Session Expired')], default='PENDING', max_length=20),
        ),
    ]
