"""
Class Academic Analysis PDF Exporter using ReportLab Platypus.

Builds a publication-grade, multi-page academic cohort analysis PDF
strictly scoped to class-level metrics using data from build_class_report_data.
"""

from __future__ import annotations

import io
from datetime import datetime
from typing import Any, Dict

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.pdfgen import canvas
from reportlab.platypus import (
    HRFlowable,
    KeepTogether,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from ..data_builders.base import safe_float


class ClassNumberedCanvas(canvas.Canvas):
    """
    Two-pass canvas to dynamically compute total pages and institutional footer
    for Class Cohort Analysis reports.
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_footer(num_pages)
            super().showPage()
        super().save()

    def draw_footer(self, page_count: int):
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#64748B"))

        page_w, _ = self._pagesize
        margin = 36

        self.setStrokeColor(colors.HexColor("#CBD5E1"))
        self.setLineWidth(0.5)
        self.line(margin, 38, page_w - margin, 38)

        self.drawString(margin, 24, "Generated by JnU Analyzer — Class Cohort Analysis")
        self.drawRightString(page_w - margin, 24, f"Page {self._pageNumber} of {page_count}")
        self.restoreState()


def build_class_pdf(report_data: Dict[str, Any]) -> bytes:
    """
    Generates a high-fidelity PDF document for the class cohort analysis report.

    Args:
        report_data: Dict output from build_class_report_data()

    Returns:
        Raw PDF file bytes.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=36,
        rightMargin=36,
        topMargin=36,
        bottomMargin=50,
    )

    styles = getSampleStyleSheet()

    # Executive Academic Typography & Palette
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=17,
        leading=21,
        textColor=colors.HexColor('#0F172A'),
    )
    subtitle_style = ParagraphStyle(
        'DocSubtitle',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=9.5,
        leading=13,
        textColor=colors.HexColor('#475569'),
    )
    section_heading = ParagraphStyle(
        'SectionHeading',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=11,
        leading=14,
        textColor=colors.HexColor('#0F172A'),
        spaceBefore=10,
        spaceAfter=4,
    )
    meta_label_style = ParagraphStyle(
        'MetaLabel',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=8,
        leading=11,
        textColor=colors.HexColor('#475569'),
    )
    meta_val_style = ParagraphStyle(
        'MetaVal',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=8,
        leading=11,
        textColor=colors.HexColor('#0F172A'),
    )
    kpi_label = ParagraphStyle(
        'KPILabel',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=7,
        leading=9,
        textColor=colors.HexColor('#64748B'),
        alignment=1,
    )
    kpi_val = ParagraphStyle(
        'KPIValue',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=12.5,
        leading=15,
        textColor=colors.HexColor('#0F172A'),
        alignment=1,
    )
    table_cell = ParagraphStyle(
        'TableCell',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=7.5,
        leading=10,
        textColor=colors.HexColor('#1E293B'),
    )
    table_cell_bold = ParagraphStyle(
        'TableCellBold',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=7.5,
        leading=10,
        textColor=colors.HexColor('#0F172A'),
    )
    table_header = ParagraphStyle(
        'TableHeader',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=7.5,
        leading=10,
        textColor=colors.HexColor('#FFFFFF'),
        alignment=1,
    )

    story = []
    metadata = report_data.get("metadata", {})
    class_ov = report_data.get("class_overview", {})
    cum_ov = report_data.get("cumulative_overview", {})
    rankings = report_data.get("student_rankings", [])
    subjects = report_data.get("subject_analysis", [])

    # 1. Header Banner
    story.append(Paragraph("JnU Analyzer", ParagraphStyle('Brand', fontName='Helvetica-Bold', fontSize=10, textColor=colors.HexColor('#0F172A'))))
    story.append(Paragraph("Class Academic Analysis", title_style))
    inst_line = f"{metadata.get('institution', 'Jagannath University')} • {metadata.get('department', 'Department of Computer Science & Engineering')}"
    story.append(Paragraph(inst_line, subtitle_style))
    if metadata.get('semester'):
        sem_line = f"{metadata.get('semester')}"
        if metadata.get('exam_session'):
            sem_line += f" (Session: {metadata.get('exam_session')})"
        story.append(Paragraph(sem_line, subtitle_style))

    story.append(Spacer(1, 6))
    story.append(HRFlowable(width="100%", thickness=1.0, color=colors.HexColor('#0F172A'), spaceAfter=8))

    # 2. Institutional & Dataset Context Box
    gen_time_str = datetime.now().strftime("%B %d, %Y • %I:%M %p")
    meta_table_data = [
        [
            Paragraph("Total Students:", meta_label_style),
            Paragraph(f"<b>{class_ov.get('total_students', len(rankings))}</b> enrolled", meta_val_style),
            Paragraph("Total Subjects:", meta_label_style),
            Paragraph(f"<b>{class_ov.get('total_subjects', len(subjects))}</b> courses", meta_val_style),
        ],
        [
            Paragraph("Report Date:", meta_label_style),
            Paragraph(gen_time_str, meta_val_style),
            Paragraph("", meta_label_style),
            Paragraph("", meta_val_style),
        ],
    ]
    meta_table = Table(meta_table_data, colWidths=[110, 150, 100, 160])
    meta_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#F8FAFC')),
        ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor('#CBD5E1')),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#F1F5F9')),
        ('SPAN', (1, 1), (3, 1)),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
        ('LEFTPADDING', (0, 0), (-1, -1), 8),
        ('RIGHTPADDING', (0, 0), (-1, -1), 8),
    ]))
    story.append(meta_table)
    story.append(Spacer(1, 10))

    # 3. Class Summary KPI Grid (Mean, Median, Mode, Highest, Lowest, StdDev)
    story.append(Paragraph("Cohort Performance Summary", section_heading))

    avg_gpa = class_ov.get("average_gpa")
    med_gpa = class_ov.get("median_gpa")
    mod_gpa = class_ov.get("mode_gpa")
    hi_gpa = class_ov.get("highest_gpa")
    lo_gpa = class_ov.get("lowest_gpa")
    sd_gpa = class_ov.get("std_dev_gpa")

    kpi_data = [
        [
            Paragraph("CLASS AVERAGE GPA", kpi_label),
            Paragraph("MEDIAN GPA", kpi_label),
            Paragraph("MODE GPA", kpi_label),
            Paragraph("HIGHEST GPA", kpi_label),
            Paragraph("LOWEST GPA", kpi_label),
            Paragraph("STD DEVIATION", kpi_label),
        ],
        [
            Paragraph(f"{avg_gpa:.2f}" if avg_gpa is not None else "—", kpi_val),
            Paragraph(f"{med_gpa:.2f}" if med_gpa is not None else "—", kpi_val),
            Paragraph(f"{mod_gpa:.2f}" if mod_gpa is not None else "—", kpi_val),
            Paragraph(f"{hi_gpa:.2f}" if hi_gpa is not None else "—", kpi_val),
            Paragraph(f"{lo_gpa:.2f}" if lo_gpa is not None else "—", kpi_val),
            Paragraph(f"{sd_gpa:.2f}" if sd_gpa is not None else "—", kpi_val),
        ],
    ]
    kpi_table = Table(kpi_data, colWidths=[86, 86, 86, 86, 86, 90])
    kpi_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#FFFFFF')),
        ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor('#CBD5E1')),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E2E8F0')),
        ('TOPPADDING', (0, 0), (-1, 0), 5),
        ('BOTTOMPADDING', (0, 1), (-1, 1), 5),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
    ]))
    story.append(kpi_table)
    story.append(Spacer(1, 10))

    # 4. GPA Grade Distribution Breakdown Table
    gpa_dist = class_ov.get("gpa_distribution", [])
    if gpa_dist:
        story.append(Paragraph("UGC Standard Letter Grade Distribution", section_heading))
        dist_headers = [
            Paragraph("Grade Tier", table_header),
            Paragraph("GPA Range", table_header),
            Paragraph("Student Count", table_header),
            Paragraph("Percentage", table_header),
        ]
        dist_table_data = [dist_headers]

        for item in gpa_dist:
            grade_tier = item.get("grade_tier") or item.get("grade") or ""
            gpa_range = item.get("gpa_range") or item.get("range") or ""
            bracket = str(item.get("bracket", "")).strip()

            if not grade_tier or not gpa_range:
                if "(" in bracket and ")" in bracket:
                    parts = bracket.split("(", 1)
                    grade_tier = parts[0].strip()
                    gpa_range = parts[1].rstrip(")").strip()
                elif bracket:
                    grade_tier = bracket
                    gpa_range = "—"

            count_val = int(item.get("count", 0))
            pct_val = safe_float(item.get("percentage"), default=0.0) or 0.0

            dist_table_data.append([
                Paragraph(f"<b>{grade_tier}</b>", ParagraphStyle('D_Tier', parent=table_cell_bold, alignment=1, fontSize=8)),
                Paragraph(str(gpa_range), ParagraphStyle('D_R', parent=table_cell, alignment=1)),
                Paragraph(f"<b>{count_val}</b> {('student' if count_val == 1 else 'students')}", ParagraphStyle('D_C', parent=table_cell, alignment=1)),
                Paragraph(f"<b>{pct_val:.1f}%</b>", ParagraphStyle('D_P', parent=table_cell_bold, alignment=1)),
            ])

        dist_table = Table(dist_table_data, colWidths=[100, 150, 130, 140])
        dist_style = [
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#0F172A')),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor('#CBD5E1')),
            ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E2E8F0')),
            ('TOPPADDING', (0, 0), (-1, -1), 4),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ]
        for r_idx in range(1, len(dist_table_data)):
            if r_idx % 2 == 0:
                dist_style.append(('BACKGROUND', (0, r_idx), (-1, r_idx), colors.HexColor('#F8FAFC')))
        dist_table.setStyle(TableStyle(dist_style))
        story.append(dist_table)
        story.append(Spacer(1, 10))

    # 5. Subject-Wise Analytics Table
    story.append(Paragraph("Subject-Wise Academic Performance & Course Toppers", section_heading))
    subj_headers = [
        Paragraph("Code", table_header),
        Paragraph("Course Title", table_header),
        Paragraph("Cr", table_header),
        Paragraph("Students", table_header),
        Paragraph("Avg GP", table_header),
        Paragraph("Median", table_header),
        Paragraph("Mode", table_header),
        Paragraph("Highest", table_header),
        Paragraph("Lowest", table_header),
        Paragraph("Top Student(s)", table_header),
    ]
    subj_table_data = [subj_headers]

    for sub in subjects:
        toppers_list = sub.get("toppers", [])
        topper_strs = [f"{t.get('student_id')} ({t.get('grade_point', 0.0):.2f})" for t in toppers_list[:2]]
        topper_text = ", ".join(topper_strs) or "—"

        avg_v = sub.get("average_gp")
        med_v = sub.get("median_gp")
        mod_v = sub.get("mode_gp")
        hi_v = sub.get("highest_gp")
        lo_v = sub.get("lowest_gp")

        subj_table_data.append([
            Paragraph(str(sub.get("course_code", "")), table_cell_bold),
            Paragraph(str(sub.get("course_title", "")), table_cell),
            Paragraph(f"{sub.get('credit_hours', 3.0):.1f}", ParagraphStyle('S_Cr', parent=table_cell, alignment=1)),
            Paragraph(str(sub.get("number_of_students", 0)), ParagraphStyle('S_N', parent=table_cell, alignment=1)),
            Paragraph(f"{avg_v:.2f}" if avg_v is not None else "—", ParagraphStyle('S_A', parent=table_cell_bold, alignment=1)),
            Paragraph(f"{med_v:.2f}" if med_v is not None else "—", ParagraphStyle('S_M', parent=table_cell, alignment=1)),
            Paragraph(f"{mod_v:.2f}" if mod_v is not None else "—", ParagraphStyle('S_Mo', parent=table_cell, alignment=1)),
            Paragraph(f"{hi_v:.2f}" if hi_v is not None else "—", ParagraphStyle('S_H', parent=table_cell, alignment=1)),
            Paragraph(f"{lo_v:.2f}" if lo_v is not None else "—", ParagraphStyle('S_L', parent=table_cell, alignment=1)),
            Paragraph(topper_text, table_cell),
        ])

    subj_table = Table(subj_table_data, colWidths=[55, 125, 25, 40, 42, 40, 38, 40, 38, 77], repeatRows=1)
    subj_style = [
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#0F172A')),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor('#CBD5E1')),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E2E8F0')),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
    ]
    for r_idx in range(1, len(subj_table_data)):
        if r_idx % 2 == 0:
            subj_style.append(('BACKGROUND', (0, r_idx), (-1, r_idx), colors.HexColor('#F8FAFC')))
    subj_table.setStyle(TableStyle(subj_style))
    story.append(subj_table)
    story.append(Spacer(1, 12))

    # 6. Student Leaderboard / Rankings Table (Repeats headers on multi-page)
    story.append(Paragraph("Complete Student Merit Leaderboard", section_heading))
    rank_headers = [
        Paragraph("Rank", table_header),
        Paragraph("Student ID", table_header),
        Paragraph("Student Name", table_header),
        Paragraph("Semester GPA", table_header),
        Paragraph("Cumulative CGPA", table_header),
        Paragraph("Sem Rank", table_header),
        Paragraph("Cum Rank", table_header),
        Paragraph("Status", table_header),
    ]
    rank_table_data = [rank_headers]

    for item in rankings:
        gpa_v = item.get("gpa", 0.0)
        cgpa_v = item.get("cgpa", 0.0)
        s_rank = item.get("semester_rank")
        c_rank = item.get("cumulative_rank")

        rank_table_data.append([
            Paragraph(f"<b>#{item.get('rank', '—')}</b>", ParagraphStyle('R_R', parent=table_cell_bold, alignment=1)),
            Paragraph(str(item.get("student_id", "")), table_cell_bold),
            Paragraph(str(item.get("student_name", "UNKNOWN")), table_cell),
            Paragraph(f"{gpa_v:.2f}", ParagraphStyle('R_G', parent=table_cell_bold, alignment=1)),
            Paragraph(f"{cgpa_v:.2f}" if cgpa_v > 0 else "—", ParagraphStyle('R_CG', parent=table_cell, alignment=1)),
            Paragraph(f"#{s_rank}" if s_rank else "—", ParagraphStyle('R_SR', parent=table_cell, alignment=1)),
            Paragraph(f"#{c_rank}" if c_rank else "—", ParagraphStyle('R_CR', parent=table_cell, alignment=1)),
            Paragraph(str(item.get("status", "VALID")), ParagraphStyle('R_St', parent=table_cell, alignment=1)),
        ])

    rank_table = Table(rank_table_data, colWidths=[35, 70, 160, 55, 55, 45, 45, 55], repeatRows=1)
    rank_style = [
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#0F172A')),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor('#CBD5E1')),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E2E8F0')),
        ('TOPPADDING', (0, 0), (-1, -1), 3.5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 3.5),
    ]
    for r_idx in range(1, len(rank_table_data)):
        if r_idx % 2 == 0:
            rank_style.append(('BACKGROUND', (0, r_idx), (-1, r_idx), colors.HexColor('#F8FAFC')))
    rank_table.setStyle(TableStyle(rank_style))
    story.append(rank_table)

    # Build document
    doc.build(story, canvasmaker=ClassNumberedCanvas)
    return buffer.getvalue()
