"""
Student Comparison PDF Exporter using ReportLab Platypus.

Builds a publication-grade, multi-page head-to-head academic comparison PDF
strictly scoped to Student A and Student B using data from build_comparison_report_data.
"""

from __future__ import annotations

import io
from datetime import datetime
from typing import Any, Dict

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.pdfgen import canvas
from reportlab.platypus import (
    HRFlowable,
    KeepTogether,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from ..data_builders.base import safe_float


class ComparisonNumberedCanvas(canvas.Canvas):
    """
    Two-pass canvas to dynamically compute total pages and institutional footer
    for Student Head-to-Head Comparison reports.
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_footer(num_pages)
            super().showPage()
        super().save()

    def draw_footer(self, page_count: int):
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#64748B"))

        page_w, _ = self._pagesize
        margin = 36

        self.setStrokeColor(colors.HexColor("#CBD5E1"))
        self.setLineWidth(0.5)
        self.line(margin, 38, page_w - margin, 38)

        self.drawString(margin, 24, "Generated by JnU Analyzer — Comparative Academic Analytics")
        self.drawRightString(page_w - margin, 24, f"Page {self._pageNumber} of {page_count}")
        self.restoreState()


def build_comparison_pdf(report_data: Dict[str, Any]) -> bytes:
    """
    Generates a high-fidelity PDF document for the student comparison report.

    Args:
        report_data: Dict output from build_comparison_report_data()

    Returns:
        Raw PDF file bytes.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=36,
        rightMargin=36,
        topMargin=36,
        bottomMargin=50,
    )

    styles = getSampleStyleSheet()

    # Executive Academic Typography & Palette
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=17,
        leading=21,
        textColor=colors.HexColor('#0F172A'),
    )
    subtitle_style = ParagraphStyle(
        'DocSubtitle',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=9.5,
        leading=13,
        textColor=colors.HexColor('#475569'),
    )
    section_heading = ParagraphStyle(
        'SectionHeading',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=11,
        leading=14,
        textColor=colors.HexColor('#0F172A'),
        spaceBefore=10,
        spaceAfter=4,
    )
    kpi_label = ParagraphStyle(
        'KPILabel',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=7,
        leading=9,
        textColor=colors.HexColor('#64748B'),
        alignment=1,
    )
    kpi_val = ParagraphStyle(
        'KPIValue',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=12.5,
        leading=15,
        textColor=colors.HexColor('#0F172A'),
        alignment=1,
    )
    table_cell = ParagraphStyle(
        'TableCell',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=7.5,
        leading=10,
        textColor=colors.HexColor('#1E293B'),
    )
    table_cell_bold = ParagraphStyle(
        'TableCellBold',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=7.5,
        leading=10,
        textColor=colors.HexColor('#0F172A'),
    )
    table_header = ParagraphStyle(
        'TableHeader',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=7.5,
        leading=10,
        textColor=colors.HexColor('#FFFFFF'),
        alignment=1,
    )

    story = []
    metadata = report_data.get("metadata", {})
    stu_a = report_data.get("student_a", {})
    stu_b = report_data.get("student_b", {})
    deltas = report_data.get("deltas", {})
    tally = report_data.get("subject_tally", {})
    courses_comp = report_data.get("course_comparison", [])

    # 1. Header Banner
    story.append(Paragraph("JnU Analyzer", ParagraphStyle('Brand', fontName='Helvetica-Bold', fontSize=10, textColor=colors.HexColor('#0F172A'))))
    story.append(Paragraph("Student Comparison Analysis", title_style))
    inst_line = f"{metadata.get('institution', 'Jagannath University')} • {metadata.get('department', 'Department of Computer Science & Engineering')}"
    story.append(Paragraph(inst_line, subtitle_style))
    if metadata.get('semester'):
        sem_line = f"{metadata.get('semester')}"
        if metadata.get('exam_session'):
            sem_line += f" (Session: {metadata.get('exam_session')})"
        story.append(Paragraph(sem_line, subtitle_style))

    story.append(Spacer(1, 6))
    story.append(HRFlowable(width="100%", thickness=1.0, color=colors.HexColor('#0F172A'), spaceAfter=8))

    # 2. Compared Candidates Banner Box
    gen_time_str = datetime.now().strftime("%B %d, %Y • %I:%M %p")
    cand_a_name = stu_a.get("student_name", "STUDENT A")
    cand_a_id = stu_a.get("student_id", "N/A")
    cand_b_name = stu_b.get("student_name", "STUDENT B")
    cand_b_id = stu_b.get("student_id", "N/A")

    cand_table_data = [
        [
            Paragraph("<b>Candidate A (Focus)</b>", ParagraphStyle('CA_H', parent=table_cell_bold, textColor=colors.HexColor('#0F172A'))),
            Paragraph("<b>Candidate B (Comparison)</b>", ParagraphStyle('CB_H', parent=table_cell_bold, textColor=colors.HexColor('#0F172A'))),
            Paragraph("<b>Comparison Context</b>", ParagraphStyle('CC_H', parent=table_cell_bold, textColor=colors.HexColor('#475569'))),
        ],
        [
            Paragraph(f"<b>{cand_a_name}</b><br/>ID: <b>{cand_a_id}</b>", table_cell),
            Paragraph(f"<b>{cand_b_name}</b><br/>ID: <b>{cand_b_id}</b>", table_cell),
            Paragraph(f"Courses: <b>{len(courses_comp)}</b><br/>Date: {gen_time_str}", table_cell),
        ],
    ]
    cand_table = Table(cand_table_data, colWidths=[180, 180, 160])
    cand_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#F8FAFC')),
        ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor('#CBD5E1')),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E2E8F0')),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
        ('LEFTPADDING', (0, 0), (-1, -1), 8),
        ('RIGHTPADDING', (0, 0), (-1, -1), 8),
    ]))
    story.append(cand_table)
    story.append(Spacer(1, 10))

    # 3. Overall Profile Comparison Matrix (Academic Summary Comparison)
    story.append(Paragraph("Overall Academic Profile Comparison", section_heading))

    a_gpa = stu_a.get("semester_gpa", 0.0)
    b_gpa = stu_b.get("semester_gpa", 0.0)
    a_cgpa = stu_a.get("cumulative_cgpa", 0.0)
    b_cgpa = stu_b.get("cumulative_cgpa", 0.0)
    a_srank = stu_a.get("semester_rank")
    b_srank = stu_b.get("semester_rank")
    a_crank = stu_a.get("cumulative_rank")
    b_crank = stu_b.get("cumulative_rank")
    a_cred = stu_a.get("credits_earned", 0.0)
    b_cred = stu_b.get("credits_earned", 0.0)

    gpa_diff = deltas.get("gpa_difference", round(a_gpa - b_gpa, 2))
    cgpa_diff = deltas.get("cgpa_difference", round(a_cgpa - b_cgpa, 2))

    def format_diff_str(val: float, is_rank: bool = False) -> str:
        if val is None:
            return "—"
        if is_rank:
            if val < 0:
                return f"+{abs(int(val))} Ranks Higher"
            elif val > 0:
                return f"-{int(val)} Ranks Lower"
            return "Equal Rank"
        if val > 0:
            return f"+{val:.2f} (A leads)"
        elif val < 0:
            return f"{val:.2f} (B leads)"
        return "Tied (0.00)"

    s_rank_diff = deltas.get("semester_rank_difference")
    c_rank_diff = deltas.get("cumulative_rank_difference")

    profile_headers = [
        Paragraph("Performance Metric", table_header),
        Paragraph(f"Student A ({cand_a_id})", table_header),
        Paragraph(f"Student B ({cand_b_id})", table_header),
        Paragraph("Comparative Delta (A vs B)", table_header),
    ]
    profile_data = [
        profile_headers,
        [
            Paragraph("Semester GPA", table_cell_bold),
            Paragraph(f"<b>{a_gpa:.2f}</b>", ParagraphStyle('GPA_A', parent=table_cell_bold, alignment=1)),
            Paragraph(f"<b>{b_gpa:.2f}</b>", ParagraphStyle('GPA_B', parent=table_cell_bold, alignment=1)),
            Paragraph(format_diff_str(gpa_diff), ParagraphStyle('D_GPA', parent=table_cell_bold, alignment=1)),
        ],
        [
            Paragraph("Semester Class Rank", table_cell_bold),
            Paragraph(f"#{a_srank}" if a_srank else "—", ParagraphStyle('SR_A', parent=table_cell, alignment=1)),
            Paragraph(f"#{b_srank}" if b_srank else "—", ParagraphStyle('SR_B', parent=table_cell, alignment=1)),
            Paragraph(format_diff_str(s_rank_diff, is_rank=True) if s_rank_diff is not None else "—", ParagraphStyle('D_SR', parent=table_cell, alignment=1)),
        ],
        [
            Paragraph("Cumulative CGPA", table_cell_bold),
            Paragraph(f"<b>{a_cgpa:.2f}</b>" if a_cgpa > 0 else "—", ParagraphStyle('CGPA_A', parent=table_cell, alignment=1)),
            Paragraph(f"<b>{b_cgpa:.2f}</b>" if b_cgpa > 0 else "—", ParagraphStyle('CGPA_B', parent=table_cell, alignment=1)),
            Paragraph(format_diff_str(cgpa_diff) if (a_cgpa > 0 or b_cgpa > 0) else "—", ParagraphStyle('D_CGPA', parent=table_cell, alignment=1)),
        ],
        [
            Paragraph("Cumulative Class Rank", table_cell_bold),
            Paragraph(f"#{a_crank}" if a_crank else "—", ParagraphStyle('CR_A', parent=table_cell, alignment=1)),
            Paragraph(f"#{b_crank}" if b_crank else "—", ParagraphStyle('CR_B', parent=table_cell, alignment=1)),
            Paragraph(format_diff_str(c_rank_diff, is_rank=True) if c_rank_diff is not None else "—", ParagraphStyle('D_CR', parent=table_cell, alignment=1)),
        ],
        [
            Paragraph("Credits Earned", table_cell_bold),
            Paragraph(f"{a_cred:.1f}", ParagraphStyle('CR_A', parent=table_cell, alignment=1)),
            Paragraph(f"{b_cred:.1f}", ParagraphStyle('CR_B', parent=table_cell, alignment=1)),
            Paragraph(f"{a_cred - b_cred:+.1f} Cr" if a_cred != b_cred else "Equal (0.0 Cr)", ParagraphStyle('D_Crd', parent=table_cell, alignment=1)),
        ],
        [
            Paragraph("Result Status", table_cell_bold),
            Paragraph(str(stu_a.get("result_status", "PASSED")), ParagraphStyle('St_A', parent=table_cell_bold, alignment=1)),
            Paragraph(str(stu_b.get("result_status", "PASSED")), ParagraphStyle('St_B', parent=table_cell_bold, alignment=1)),
            Paragraph("Verified", ParagraphStyle('St_D', parent=table_cell, alignment=1, textColor=colors.HexColor('#64748B'))),
        ],
    ]

    profile_table = Table(profile_data, colWidths=[140, 120, 120, 140])
    p_style = [
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#0F172A')),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor('#CBD5E1')),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E2E8F0')),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
    ]
    for r_idx in range(1, len(profile_data)):
        if r_idx % 2 == 0:
            p_style.append(('BACKGROUND', (0, r_idx), (-1, r_idx), colors.HexColor('#F8FAFC')))
    profile_table.setStyle(TableStyle(p_style))
    story.append(profile_table)
    story.append(Spacer(1, 10))

    # 4. Subject Outcome Tally Summary Grid
    story.append(Paragraph("Head-to-Head Subject Win/Loss Summary", section_heading))
    a_wins = tally.get("student_a_wins", 0)
    b_wins = tally.get("student_b_wins", 0)
    ties = tally.get("ties", 0)

    tally_data = [
        [
            Paragraph(f"STUDENT A WINS ({cand_a_id})", kpi_label),
            Paragraph(f"STUDENT B WINS ({cand_b_id})", kpi_label),
            Paragraph("TIED / EQUAL SUBJECTS", kpi_label),
            Paragraph("AVERAGE GP DELTA", kpi_label),
        ],
        [
            Paragraph(f"{a_wins} Subjects", kpi_val),
            Paragraph(f"{b_wins} Subjects", kpi_val),
            Paragraph(f"{ties} Subjects", kpi_val),
            Paragraph(f"{deltas.get('average_gp_difference', 0.0):+.2f}", kpi_val),
        ],
    ]
    tally_table = Table(tally_data, colWidths=[130, 130, 130, 130])
    tally_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#FFFFFF')),
        ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor('#CBD5E1')),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E2E8F0')),
        ('TOPPADDING', (0, 0), (-1, 0), 5),
        ('BOTTOMPADDING', (0, 1), (-1, 1), 5),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
    ]))
    story.append(tally_table)
    story.append(Spacer(1, 12))

    # 5. Course-by-Course Comparative Breakdown Table
    story.append(Paragraph("Course-by-Course Comparative Breakdown", section_heading))
    course_headers = [
        Paragraph("Code", table_header),
        Paragraph("Course Title", table_header),
        Paragraph("Cr", table_header),
        Paragraph(f"Student A<br/>({cand_a_id})", table_header),
        Paragraph(f"Student B<br/>({cand_b_id})", table_header),
        Paragraph("Delta (Δ)", table_header),
        Paragraph("Better Performer", table_header),
        Paragraph("Class Avg", table_header),
    ]
    course_table_data = [course_headers]

    for c in courses_comp:
        a_gp_v = c.get("student_a_gp")
        a_gr_v = c.get("student_a_grade", "")
        b_gp_v = c.get("student_b_gp")
        b_gr_v = c.get("student_b_grade", "")
        delta_v = c.get("delta_gp", 0.0)
        better = c.get("better_performer", "N/A")
        c_avg = c.get("cohort_average_gp")

        a_str = f"<b>{a_gp_v:.2f}</b> ({a_gr_v})" if a_gp_v is not None else "—"
        b_str = f"<b>{b_gp_v:.2f}</b> ({b_gr_v})" if b_gp_v is not None else "—"

        delta_str = f"{delta_v:+.2f}" if delta_v != 0.0 else "0.00"

        if better == "STUDENT_A":
            better_str = f"<b>Student A ({cand_a_id})</b>"
        elif better == "STUDENT_B":
            better_str = f"<b>Student B ({cand_b_id})</b>"
        else:
            better_str = "Tied"

        course_table_data.append([
            Paragraph(str(c.get("course_code", "")), table_cell_bold),
            Paragraph(str(c.get("course_title", "")), table_cell),
            Paragraph(f"{c.get('credits', 3.0):.1f}", ParagraphStyle('C_Cr', parent=table_cell, alignment=1)),
            Paragraph(a_str, ParagraphStyle('C_A', parent=table_cell, alignment=1)),
            Paragraph(b_str, ParagraphStyle('C_B', parent=table_cell, alignment=1)),
            Paragraph(delta_str, ParagraphStyle('C_D', parent=table_cell_bold, alignment=1)),
            Paragraph(better_str, ParagraphStyle('C_P', parent=table_cell, alignment=1)),
            Paragraph(f"{c_avg:.2f}" if c_avg is not None else "—", ParagraphStyle('C_Avg', parent=table_cell, alignment=1)),
        ])

    course_table = Table(course_table_data, colWidths=[55, 145, 25, 65, 65, 45, 80, 40], repeatRows=1)
    c_style = [
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#0F172A')),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor('#CBD5E1')),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E2E8F0')),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
    ]
    for r_idx in range(1, len(course_table_data)):
        if r_idx % 2 == 0:
            c_style.append(('BACKGROUND', (0, r_idx), (-1, r_idx), colors.HexColor('#F8FAFC')))
    course_table.setStyle(TableStyle(c_style))
    story.append(course_table)

    # Build document
    doc.build(story, canvasmaker=ComparisonNumberedCanvas)
    return buffer.getvalue()
