"""
Student Academic Analysis PDF Exporter using ReportLab Platypus.

Builds a professional, multi-page, publication-grade academic scorecard PDF
strictly scoped to the selected student using data from build_student_report_data.
"""

from __future__ import annotations

import io
from datetime import datetime
from typing import Any, Dict

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.pdfgen import canvas
from reportlab.platypus import (
    HRFlowable,
    KeepTogether,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from ..data_builders.base import get_letter_grade_from_gpa


class NumberedCanvas(canvas.Canvas):
    """
    Two-pass canvas to dynamically compute and draw exact total page numbers
    and professional institutional footer.
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_footer(num_pages)
            super().showPage()
        super().save()

    def draw_footer(self, page_count: int):
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#64748B"))

        page_w, _ = self._pagesize
        margin = 36

        # Thin rule above footer
        self.setStrokeColor(colors.HexColor("#CBD5E1"))
        self.setLineWidth(0.5)
        self.line(margin, 38, page_w - margin, 38)

        # Footer Left & Right
        self.drawString(margin, 24, "Generated by JnU Analyzer — Academic Analytics")
        self.drawRightString(page_w - margin, 24, f"Page {self._pageNumber} of {page_count}")
        self.restoreState()


def build_student_pdf(report_data: Dict[str, Any]) -> bytes:
    """
    Generates a high-fidelity PDF document for the student analysis report.

    Args:
        report_data: Dict output from build_student_report_data()

    Returns:
        Raw PDF file bytes.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=36,
        rightMargin=36,
        topMargin=36,
        bottomMargin=50,
    )

    styles = getSampleStyleSheet()

    # Executive Academic Typography & Palette (Restrained, Professional)
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=17,
        leading=21,
        textColor=colors.HexColor('#0F172A'),
    )
    subtitle_style = ParagraphStyle(
        'DocSubtitle',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=9.5,
        leading=13,
        textColor=colors.HexColor('#475569'),
    )
    section_heading = ParagraphStyle(
        'SectionHeading',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=11,
        leading=14,
        textColor=colors.HexColor('#0F172A'),
        spaceBefore=8,
        spaceAfter=4,
    )
    meta_label_style = ParagraphStyle(
        'MetaLabel',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=8,
        leading=11,
        textColor=colors.HexColor('#475569'),
    )
    meta_val_style = ParagraphStyle(
        'MetaVal',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=8,
        leading=11,
        textColor=colors.HexColor('#0F172A'),
    )
    kpi_label = ParagraphStyle(
        'KPILabel',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=7,
        leading=9,
        textColor=colors.HexColor('#64748B'),
        alignment=1,  # Center
    )
    kpi_val = ParagraphStyle(
        'KPIValue',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=13,
        leading=16,
        textColor=colors.HexColor('#0F172A'),
        alignment=1,
    )
    table_cell = ParagraphStyle(
        'TableCell',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=7.5,
        leading=10,
        textColor=colors.HexColor('#1E293B'),
    )
    table_cell_bold = ParagraphStyle(
        'TableCellBold',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=7.5,
        leading=10,
        textColor=colors.HexColor('#0F172A'),
    )
    table_header = ParagraphStyle(
        'TableHeader',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=7.5,
        leading=10,
        textColor=colors.HexColor('#FFFFFF'),
        alignment=1,
    )

    story = []
    metadata = report_data.get("metadata", {})
    student_info = report_data.get("student_info", {})
    academic = report_data.get("academic_summary", {})
    subjects = report_data.get("subject_results", [])
    stats = report_data.get("performance_statistics", {})

    # 1. Header Banner
    story.append(Paragraph("JnU Analyzer", ParagraphStyle('Brand', fontName='Helvetica-Bold', fontSize=10, textColor=colors.HexColor('#0F172A'))))
    story.append(Paragraph("Student Academic Analysis", title_style))
    inst_line = f"{metadata.get('institution', 'Jagannath University')} • {metadata.get('department', 'Department of Computer Science & Engineering')}"
    story.append(Paragraph(inst_line, subtitle_style))
    if metadata.get('semester'):
        sem_line = f"{metadata.get('semester')}"
        if metadata.get('exam_session'):
            sem_line += f" (Session: {metadata.get('exam_session')})"
        story.append(Paragraph(sem_line, subtitle_style))

    story.append(Spacer(1, 6))
    story.append(HRFlowable(width="100%", thickness=1.0, color=colors.HexColor('#0F172A'), spaceAfter=8))

    # 2. Student Identity & Context Box
    gen_time_str = datetime.now().strftime("%B %d, %Y • %I:%M %p")
    meta_table_data = [
        [
            Paragraph("Student Name:", meta_label_style),
            Paragraph(str(student_info.get("student_name", "UNKNOWN")), meta_val_style),
            Paragraph("Student ID:", meta_label_style),
            Paragraph(str(student_info.get("student_id", "N/A")), meta_val_style),
        ],
        [
            Paragraph("Merit Serial / Status:", meta_label_style),
            Paragraph(f"#{student_info.get('serial_no', 'N/A')} ({student_info.get('status', 'VALID')})", meta_val_style),
            Paragraph("Report Date:", meta_label_style),
            Paragraph(gen_time_str, meta_val_style),
        ],
    ]
    meta_table = Table(meta_table_data, colWidths=[110, 150, 90, 170])
    meta_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#F8FAFC')),
        ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor('#CBD5E1')),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#F1F5F9')),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
        ('LEFTPADDING', (0, 0), (-1, -1), 8),
        ('RIGHTPADDING', (0, 0), (-1, -1), 8),
    ]))
    story.append(meta_table)
    story.append(Spacer(1, 10))

    # 3. Academic Summary KPIs (5 Cards Grid)
    story.append(Paragraph("Academic Performance Summary", section_heading))
    
    sem_gpa = academic.get("semester_gpa", 0.0)
    sem_rank = academic.get("semester_rank")
    sem_pct = academic.get("semester_percentile")
    cum_cgpa = academic.get("cumulative_cgpa", 0.0)
    cum_rank = academic.get("cumulative_rank")
    cum_pct = academic.get("cumulative_percentile")
    earned_cr = academic.get("credits_earned", 0.0)
    tot_subj = academic.get("total_subjects", 0)

    rank_str = f"#{sem_rank}" if sem_rank else "—"
    if sem_pct:
        rank_str += f" ({sem_pct}%)"

    cum_rank_str = f"#{cum_rank}" if cum_rank else "—"
    if cum_pct:
        cum_rank_str += f" ({cum_pct}%)"

    kpi_data = [
        [
            Paragraph("SEMESTER GPA", kpi_label),
            Paragraph("SEMESTER RANK", kpi_label),
            Paragraph("CUMULATIVE CGPA", kpi_label),
            Paragraph("CUMULATIVE RANK", kpi_label),
            Paragraph("CREDITS & SUBJECTS", kpi_label),
        ],
        [
            Paragraph(f"{sem_gpa:.2f}", kpi_val),
            Paragraph(rank_str, kpi_val),
            Paragraph(f"{cum_cgpa:.2f}" if cum_cgpa > 0 else "N/A", kpi_val),
            Paragraph(cum_rank_str, kpi_val),
            Paragraph(f"{earned_cr:.1f} Cr ({tot_subj})", ParagraphStyle('KD', parent=kpi_val, fontSize=10.5)),
        ],
    ]
    kpi_table = Table(kpi_data, colWidths=[104, 104, 104, 104, 104])
    kpi_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#FFFFFF')),
        ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor('#CBD5E1')),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E2E8F0')),
        ('TOPPADDING', (0, 0), (-1, 0), 5),
        ('BOTTOMPADDING', (0, 1), (-1, 1), 5),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
    ]))
    story.append(kpi_table)
    story.append(Spacer(1, 12))

    # 4. Subject Results Table (Repeats headers across pages automatically)
    story.append(Paragraph("Subject-Wise Academic Results", section_heading))

    table_data = [
        [
            Paragraph("Course Code", table_header),
            Paragraph("Course Title", table_header),
            Paragraph("Credit", table_header),
            Paragraph("Grade Point", table_header),
            Paragraph("Letter Grade", table_header),
            Paragraph("Subject Rank", table_header),
            Paragraph("Class Highest", table_header),
            Paragraph("Class Avg", table_header),
        ]
    ]

    for sub in subjects:
        gp_v = sub.get("grade_point")
        gp_text = f"{gp_v:.2f}" if gp_v is not None else "—"
        lg_text = sub.get("letter_grade") or "—"
        s_rank = sub.get("subject_rank")
        s_rank_text = f"#{s_rank}" if s_rank else "—"
        hi_gp = sub.get("class_highest_gp")
        hi_text = f"{hi_gp:.2f}" if hi_gp is not None else "—"
        avg_gp = sub.get("class_average_gp")
        avg_text = f"{avg_gp:.2f}" if avg_gp is not None else "—"

        table_data.append([
            Paragraph(str(sub.get("course_code", "")), table_cell_bold),
            Paragraph(str(sub.get("course_title", "")), table_cell),
            Paragraph(f"{sub.get('credit', 3.0):.1f}", ParagraphStyle('TC_C', parent=table_cell, alignment=1)),
            Paragraph(gp_text, ParagraphStyle('TC_GP', parent=table_cell_bold, alignment=1)),
            Paragraph(lg_text, ParagraphStyle('TC_LG', parent=table_cell_bold, alignment=1)),
            Paragraph(s_rank_text, ParagraphStyle('TC_R', parent=table_cell, alignment=1)),
            Paragraph(hi_text, ParagraphStyle('TC_H', parent=table_cell_bold, alignment=1)),
            Paragraph(avg_text, ParagraphStyle('TC_A', parent=table_cell, alignment=1, textColor=colors.HexColor('#64748B'))),
        ])

    subject_table = Table(table_data, colWidths=[68, 164, 36, 48, 48, 50, 54, 52], repeatRows=1)
    
    # Clean table styling with alternating rows
    t_style = [
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#0F172A')),  # Dark header
        ('ALIGN', (0, 0), (-1, 0), 'CENTER'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor('#CBD5E1')),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E2E8F0')),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
    ]

    for row_idx in range(1, len(table_data)):
        if row_idx % 2 == 0:
            t_style.append(('BACKGROUND', (0, row_idx), (-1, row_idx), colors.HexColor('#F8FAFC')))

    subject_table.setStyle(TableStyle(t_style))
    story.append(subject_table)
    story.append(Spacer(1, 12))

    # 5. Student Performance Insights Box
    story.append(Paragraph("Student Performance Insights", section_heading))

    highest_gp_val = stats.get("highest_subject_gp")
    lowest_gp_val = stats.get("lowest_subject_gp")
    avg_gp_val = stats.get("average_subject_gp")
    highest_courses = ", ".join(stats.get("highest_subject_courses", [])) or "—"
    lowest_courses = ", ".join(stats.get("lowest_subject_courses", [])) or "—"

    # Status normalization with grade display (e.g. "PASSED (A+)" or "PASSED (A)")
    raw_status = str(academic.get('semester_result_status') or student_info.get('status') or 'PASSED').strip().upper()
    gpa_grade = get_letter_grade_from_gpa(sem_gpa)

    if raw_status in ('P', 'PASS', 'PASSED'):
        status_label = f"PASSED ({gpa_grade})"
        status_color = '#0F766E'  # Academic deep teal
        status_detail = f"Official semester standing with grade {gpa_grade}"
    elif raw_status in ('F', 'FAIL', 'FAILED'):
        status_label = "FAILED"
        status_color = '#991B1B'  # Deep red
        status_detail = "Did not meet promotional criteria"
    elif raw_status in ('W', 'WITHHELD'):
        status_label = "WITHHELD"
        status_color = '#92400E'  # Muted dark amber
        status_detail = "Results under institutional review"
    else:
        status_label = f"{raw_status} ({gpa_grade})"
        status_color = '#0F766E'
        status_detail = f"Official semester record (Grade: {gpa_grade})"

    def make_insight_cell(label: str, value_text: str, value_color: str, detail_text: str):
        return [
            Paragraph(label, ParagraphStyle('InsLabel', parent=styles['Normal'], fontName='Helvetica-Bold', fontSize=7, leading=9, textColor=colors.HexColor('#64748B'))),
            Spacer(1, 2),
            Paragraph(value_text, ParagraphStyle('InsVal', parent=styles['Normal'], fontName='Helvetica-Bold', fontSize=12.5, leading=15, textColor=colors.HexColor(value_color))),
            Spacer(1, 2),
            Paragraph(detail_text, ParagraphStyle('InsDetail', parent=styles['Normal'], fontName='Helvetica', fontSize=7.5, leading=10, textColor=colors.HexColor('#334155'))),
        ]

    perf_data = [
        [
            make_insight_cell(
                "HIGHEST SUBJECT GP",
                f"{highest_gp_val:.2f}" if highest_gp_val is not None else "—",
                "#0F172A",
                f"Achieved in {highest_courses}" if highest_gp_val is not None else "No course data available",
            ),
            make_insight_cell(
                "LOWEST SUBJECT GP",
                f"{lowest_gp_val:.2f}" if lowest_gp_val is not None else "—",
                "#0F172A",
                f"Recorded in {lowest_courses}" if lowest_gp_val is not None else "No course data available",
            ),
        ],
        [
            make_insight_cell(
                "AVERAGE SUBJECT GP",
                f"{avg_gp_val:.2f}" if avg_gp_val is not None else "—",
                "#0F172A",
                f"Calculated average across all {len(subjects)} completed courses",
            ),
            make_insight_cell(
                "SEMESTER RESULT STATUS",
                status_label,
                status_color,
                status_detail,
            ),
        ],
    ]

    perf_table = Table(perf_data, colWidths=[255, 255])
    perf_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#F8FAFC')),
        ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor('#CBD5E1')),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E2E8F0')),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('LEFTPADDING', (0, 0), (-1, -1), 8),
        ('RIGHTPADDING', (0, 0), (-1, -1), 8),
    ]))
    story.append(KeepTogether([perf_table]))

    # Build the document with two-pass canvas for page numbering
    doc.build(story, canvasmaker=NumberedCanvas)
    return buffer.getvalue()
